Tagging support
kanisterio/kanister pull request #1146
Opened 2021-11-23 23:47 UTC by bathina2

## Change Overview

The following PR introduces the snapshot tagging for vsphere

## Pull request type

Please check the type of change your PR introduces:
- [ ] :construction: Work in Progress
- [ ] :rainbow: Refactoring (no functional changes, no api changes)
- [ ] :hamster: Trivial/Minor
- [ ] :bug: Bugfix
- [x] :sunflower: Feature
- [ ] :world_map: Documentation
- [ ] :robot: Test

## Issues

- #XXX

## Test Plan

- [ ] :muscle: Manual
- [ ] :zap: Unit test
- [ ] :green_heart: E2E

2021-11-29 21:27 UTC, denisvmedia commented on pkg/blockstorage/vmware/vmware.go
> +		for k, v := range tags {
These two lines look suspicious to me. If there is now error in the `if` condition, then probably there is no need in `for`.

2021-12-06 22:02 UTC, carlbraganza commented on pkg/blockstorage/vmware/vmware.go
> +	tm := vapitags.NewManager(c)
Expose the actual tagging cli

2021-12-06 22:03 UTC, carlbraganza commented on pkg/blockstorage/vmware/vmware.go
> +		TagManager: tm,
Expose the tagging client and hide your interface.

2021-12-06 22:04 UTC, carlbraganza commented on pkg/blockstorage/vmware/vmware.go
> +	TagManager tagManager
Expose the tagging service client too - the `FcdProvider` type is used in CBT which could need it over time.

Hide your internal interface variable - it is really tacky anyway to expose a variable to an internal interface.

2021-12-06 22:07 UTC, carlbraganza commented on pkg/blockstorage/vmware/vmware.go
> +	cat, err := p.TagManager.GetCategory(ctx, categoryName)
Why not use `p.GetCategoryID` here?

2021-12-06 22:07 UTC, carlbraganza commented on pkg/blockstorage/vmware/vmware.go
> +func (t *snapshotTag) print() string {
This signature should be `String() string`.

2021-12-06 22:09 UTC, carlbraganza commented on pkg/blockstorage/vmware/vmware.go
> +type snapshotTag struct {
Should use a prefix of `vmWare` or `VMware`.

Why not expose the type?

2021-12-06 22:10 UTC, carlbraganza commented on pkg/blockstorage/vmware/vmware.go
> +func (p *FcdProvider) setTagsSnapshot(ctx context.Context, snapshot *blockstorage.Snapshot, tags map[string]string) error {
`setSnapshotTags`

2021-12-06 22:10 UTC, carlbraganza commented on pkg/blockstorage/vmware/vmware.go
> +func (p *FcdProvider) deleteTagsSnapshot(ctx context.Context, snapshot *blockstorage.Snapshot) error {
`deleteSnapshotTags`

2021-12-06 22:11 UTC, carlbraganza commented on pkg/blockstorage/vmware/vmware.go
> +func (p *FcdProvider) parseTag(tag string) (*snapshotTag, error) {
`parseSnapshotTag`

2021-12-06 22:13 UTC, carlbraganza requested changes
See comments.

2021-12-07 18:44 UTC, carlbraganza approved these changes

2021-12-07 18:45 UTC, merged