Kopia repo wrappers 2
kanisterio/kanister pull request #1661
Opened 2022-10-05 12:31 UTC by ankitjain235

## Change Overview

## Pull request type

Please check the type of change your PR introduces:
- [ ] :construction: Work in Progress
- [ ] :rainbow: Refactoring (no functional changes, no api changes)
- [ ] :hamster: Trivial/Minor
- [ ] :bug: Bugfix
- [ ] :sunflower: Feature
- [ ] :world_map: Documentation
- [ ] :robot: Test

## Issues 

- fixes #issue-number

## Test Plan

- [ ] :muscle: Manual
- [ ] :zap: Unit test
- [ ] :green_heart: E2E

2022-10-10 06:13 UTC, shlokc9 commented on pkg/kopia/repository/create.go
> +)
These error messages are already present in `pkg/kopia/errors/errors.go`
Can we make use of those?

2022-10-10 06:49 UTC, shlokc9 commented on pkg/kopia/repository/create.go
> +
These constant flags can be moved to `github.com/kanisterio/kanister/pkg/kopia/command/const.go`

2022-10-10 06:50 UTC, shlokc9 requested changes
Suggested some minor changes

2022-10-21 18:47 UTC, ankitjain235 commented
The workflow has been changed and separate PRs have been raised. Closing this PR.

2022-10-21 18:47 UTC, closed without merging