[WIP] Postgres to RDS blueprint
kanisterio/kanister pull request #1763
Opened 2022-11-29 18:55 UTC by akankshakumari393

## Change Overview

## Pull request type

Please check the type of change your PR introduces:
- [ ] :construction: Work in Progress
- [ ] :rainbow: Refactoring (no functional changes, no api changes)
- [ ] :hamster: Trivial/Minor
- [ ] :bug: Bugfix
- [ ] :sunflower: Feature
- [ ] :world_map: Documentation
- [ ] :robot: Test

## Issues 

- fixes #issue-number

## Test Plan

- [ ] :muscle: Manual
- [ ] :zap: Unit test
- [ ] :green_heart: E2E

2022-11-30 15:22 UTC, viveksinghggits commented on examples/postgres-RDS/README.md
> +This example is to demonstrate how Kanister can be used to import data in AWS RDS instance from On-prem postgres using Kanister functions
```suggestion
This example is to demonstrate how Kanister can be used to import data in AWS RDS instance from On-prem Postgres using Kanister functions
```
postgres -> Postgres

2022-11-30 15:39 UTC, viveksinghggits commented on examples/postgres-RDS/README.md
> +[PostgreSQL](https://www.postgresql.org/) is an object-relational database management system (ORDBMS) with an emphasis on extensibility and on standards-compliance.
what is on standards-compliance?

2022-11-30 15:40 UTC, viveksinghggits commented on examples/postgres-RDS/README.md
> +RDS instance needs to be reachable from outside world. So make sure that you have VPC with security group having rule to allow ingress traffic on 5432 TCP port.
```suggestion
RDS instance needs to be reachable from the outside world. So make sure that you have VPC with the security group having a rule to allow ingress traffic on 5432 TCP port.
```

2022-12-01 14:23 UTC, shuguet requested changes
This security aspect has to be fixed before release.

2022-12-01 14:23 UTC, shuguet commented on examples/postgres-RDS/README.md
> +aws ec2 authorize-security-group-ingress --group-name pgtest-sg --protocol tcp --port 5432 --cidr 0.0.0.0/0
Can we add a note to say this is highly insecure and shouldn't be use in a production environment/is only good for testing?
That rule basically makes this database accessible from any source IP in the entire internet ;)

2023-02-09 06:52 UTC, pavannd1 commented
Relevant

2023-05-30 19:55 UTC, pavannd1 commented
Refactored and merged using a different PR.

2023-05-30 19:55 UTC, closed without merging