Kanister docs update to version 0.96.0
kanisterio/kanister pull request #2322
Opened 2023-09-11 11:40 UTC by infraq

Kanister docs update to version 0.96.0

2023-09-11 23:12 UTC, pavannd1 requested changes
Holding off until the end of the week.

2023-09-21 02:51 UTC, pavannd1 approved these changes

2023-09-21 02:56 UTC, pavannd1 requested changes
Found a vulnerability in the kanister-tools image. Going to fix it before merging this.

2023-09-21 07:11 UTC, pavannd1 approved these changes

2023-09-21 07:12 UTC, pavannd1 commented
Merge after #2351

2023-09-21 07:56 UTC, viveksinghggits approved these changes

2023-09-21 08:58 UTC, merged