Update azure sdk lib
kanisterio/kanister pull request #2507
Opened 2023-12-01 12:38 UTC by mabhi

## Change Overview
As per Azure guidelines, few modules from azure library are retiring support from 31 March 2023 . Due to which there is need to replace such modules with azure recommended azure-go-sdk modules.

go-autorest being used in the blockstorage package will be out of support from March 2023. Follow the documentation below to replace it with a new supported package.
https://azure.microsoft.com/en-us/updates/support-for-azure-sdk-libraries-that-do-not-conform-to-our-current-azure-sdk-guidelines-will-be-retired-as-of-31-march-2023/

## Pull request type

Please check the type of change your PR introduces:
- [ ] :construction: Work in Progress
- [x] :rainbow: Refactoring (no functional changes, no api changes)
- [ ] :hamster: Trivial/Minor
- [ ] :bug: Bugfix
- [ ] :sunflower: Feature
- [ ] :world_map: Documentation
- [ ] :robot: Test

## Test Plan

- [ ] :muscle: Manual
- [x] :zap: Unit test
- [ ] :green_heart: E2E

2023-12-06 22:55 UTC, leuyentran requested changes
For more context, the review is technically a re-review from https://github.com/kanisterio/kanister/pull/2368/ . My review strategy was mainly maing sure the changes match, albeit that was not entirely successful with `azuredisk.go` due to recent changes in this file. 

The recent changes in this file that need extra review are:

1.  [Implementation of SnapshotCreateWaitForCompletion ](https://github.com/kanisterio/kanister/pull/2494) - review added 
2. [Re-org of code from here ](https://github.com/kanisterio/kanister/pull/2236) - LGTM

2023-12-06 22:55 UTC, leuyentran commented on pkg/blockstorage/azure/azuredisk.go
> +		if err == nil && snapshot.ProvisioningState == string(armstorage.ProvisioningStateSucceeded) {
I questioned whether or not this is the correct package. When we look at the original code, the consts `azcompute.ProvisioningStateSucceeded` is part of a group of 6 const as such to indicate Provisioning states
```go
// ProvisioningState1 enumerates the values for provisioning state 1.
type ProvisioningState1 string

const (
	// ProvisioningState1Creating ...
	ProvisioningState1Creating ProvisioningState1 = "Creating"
	// ProvisioningState1Deleting ...
	ProvisioningState1Deleting ProvisioningState1 = "Deleting"
	// ProvisioningState1Failed ...
	ProvisioningState1Failed ProvisioningState1 = "Failed"
	// ProvisioningState1Migrating ...
	ProvisioningState1Migrating ProvisioningState1 = "Migrating"
	// ProvisioningState1Succeeded ...
	ProvisioningState1Succeeded ProvisioningState1 = "Succeeded"
	// ProvisioningState1Updating ...
	ProvisioningState1Updating ProvisioningState1 = "Updating"
)
```
When we look at the migrated constant `armstorage.ProvisioningStateSucceeded` here, it is part of the following group, which lacks states such as `Deleting` or `Updating`
```go
// ProvisioningState - Gets the status of the storage account at the time the operation was called.
type ProvisioningState string

const (
	ProvisioningStateCreating     ProvisioningState = "Creating"
	ProvisioningStateResolvingDNS ProvisioningState = "ResolvingDNS"
	ProvisioningStateSucceeded    ProvisioningState = "Succeeded"
)

```

2023-12-06 22:55 UTC, leuyentran commented on pkg/blockstorage/azure/azuredisk.go
> +		if err == nil && snapshot.ProvisioningState == string(armstorage.ProvisioningStateSucceeded) {
I think a more appropriate choice is [GalleryProvisioningState](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v4#GalleryProvisioningState)
```go
// GalleryProvisioningState - The provisioning state, which only appears in the response.
type GalleryProvisioningState string

const (
	GalleryProvisioningStateCreating  GalleryProvisioningState = "Creating"
	GalleryProvisioningStateDeleting  GalleryProvisioningState = "Deleting"
	GalleryProvisioningStateFailed    GalleryProvisioningState = "Failed"
	GalleryProvisioningStateMigrating GalleryProvisioningState = "Migrating"
	GalleryProvisioningStateSucceeded GalleryProvisioningState = "Succeeded"
	GalleryProvisioningStateUpdating  GalleryProvisioningState = "Updating"
)
```

2023-12-08 03:21 UTC, mabhi commented on pkg/blockstorage/helper_test.go
> +// Copyright 2019 The Kanister Authors.
Done

2023-12-08 03:23 UTC, mabhi commented on pkg/kopia/command/storage/secret_utils.go
> +	"github.com/kanisterio/kanister/pkg/blockstorage/azure"
Done

2023-12-08 03:24 UTC, mabhi commented on pkg/kopia/command/storage/secret_utils.go
> +	"time"
Done

2023-12-08 13:12 UTC, leuyentran approved these changes
LGTM, please let Pavan do another pass as well before merging

2023-12-11 19:23 UTC, merged