Removed the linter - misspel & gci
kanisterio/kanister pull request #3052
Opened 2024-08-21 13:18 UTC by anishbista60

## Change Overview

- Removed the  linter `misspell` and `gci`
## Pull request type

Please check the type of change your PR introduces:
- [ ] :construction: Work in Progress
- [ ] :rainbow: Refactoring (no functional changes, no api changes)
- [ ] :hamster: Trivial/Minor
- [ ] :bug: Bugfix
- [ ] :sunflower: Feature
- [ ] :world_map: Documentation
- [ ] :robot: Test
- [ ] :building_construction: Build

## Issues 

- fixes #2962 

## Test Plan

- [ ] :muscle: Manual
- [ ] :zap: Unit test
- [ ] :green_heart: E2E

2024-08-21 13:24 UTC, anishbista60 commented
@julio-lopez @saima-s  All changes looks fine here , as i test in my local .
 Except below three.  

```
pkg/secrets/repositoryserver/aws_secrets_test.go:19: File is not `gci`-ed with --skip-generated -s standard -s default -s prefix(github.com/kanisterio/kanister) -s blank -s dot (gci)

pkg/secrets/repositoryserver/azure_secrets_test.go:19: File is not `gci`-ed with --skip-generated -s standard -s default -s prefix(github.com/kanisterio/kanister) -s blank -s dot (gci)

pkg/secrets/repositoryserver/gcp_secrets_test.go:19: File is not `gci`-ed with --skip-generated -s standard -s default -s prefix(github.com/kanisterio/kanister) -s blank -s dot (gci)
```
what is missing here?  i have arranged these package based on 
[https://github.com/kanisterio/kanister/blob/adab42bfd592f034ece0a3b9595218b87eb84d0f/.golangci.yml#L77](url)

2024-08-23 18:39 UTC, julio-lopez requested changes

2024-08-23 18:39 UTC, julio-lopez commented on .golangci.yml
> -        - gci
☝🏼

2024-08-24 04:13 UTC, anishbista60 commented on .golangci.yml
> -        - gci
@julio-lopez Done sir .

2024-08-24 04:43 UTC, julio-lopez requested changes
Actually, the import changes need to be reverted as well.
The original ordering was correct.

It seems that the `.` import is throwing off `gci`.

2024-08-24 04:43 UTC, julio-lopez commented on pkg/secrets/repositoryserver/azure_secrets_test.go
This one should be reverted. The import order was correct before the change.

2024-08-24 04:43 UTC, julio-lopez commented on pkg/secrets/repositoryserver/aws_secrets_test.go
> +	. "gopkg.in/check.v1"
This one should be reverted. The import order was correct before the change.

```suggestion
	. "gopkg.in/check.v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	secerrors "github.com/kanisterio/kanister/pkg/secrets/errors"
```

2024-08-24 04:43 UTC, julio-lopez commented on pkg/secrets/repositoryserver/gcp_secrets_test.go
Revert this one.

2024-08-24 04:43 UTC, julio-lopez commented on pkg/secrets/repositoryserver/s3compliant_secrets_test.go
and this one

2024-08-24 04:57 UTC, anishbista60 commented
@julio-lopez i think i  should have next PR for `gci`.

2024-08-24 05:18 UTC, julio-lopez approved these changes

2024-08-24 05:19 UTC, merged