deps(docker): unpin kopia version for kanister-tools
kanisterio/kanister pull request #3063
Opened 2024-08-23 20:54 UTC by hairyhum

## Change Overview

Use current master of kopia to build kanister-tools image

## Pull request type

Please check the type of change your PR introduces:
- [ ] :construction: Work in Progress
- [ ] :rainbow: Refactoring (no functional changes, no api changes)
- [ ] :hamster: Trivial/Minor
- [ ] :bug: Bugfix
- [ ] :sunflower: Feature
- [ ] :world_map: Documentation
- [ ] :robot: Test
- [x] :building_construction: Build

## Issues 

- fixes #issue-number

## Test Plan

- [ ] :muscle: Manual
- [x] :zap: Unit test
- [ ] :green_heart: E2E

2024-08-24 00:19 UTC, julio-lopez requested changes
Unpinning may have undesired side-effects, such as
- inadvertently upgrading and picking up a different version of kopia on every build (or invocation of goreleaser).
- not being able reprodude a released version with the same version of kopia that was used when it got released.
- also, there is a specific kopia dependency in `go.mod`, which is kept in sync with the one here. The version used here should be pulled from `go.mod` at build time.

2024-08-26 16:20 UTC, hairyhum commented
> also, there is a specific kopia dependency in go.mod, which is kept in sync with the one here. The version used here should be pulled from go.mod at build time.

That's a good point, but this means we didn't keep kopia version in `go.mod` up to date. Pulling version from `go.mod` should be possible.

2024-10-11 17:13 UTC, hairyhum commented
Bumped kopia commit in go.mod and goreleaser.
Not using the latest version because we have issue updating the build image right now https://github.com/kanisterio/kanister/actions/runs/11295843718

2024-10-16 05:48 UTC, julio-lopez approved these changes

2024-10-18 05:40 UTC, merged