Enable `dupl` linter for test package
kanisterio/kanister pull request #3074
Opened 2024-08-28 11:54 UTC by anishbista60

## Change Overview

Enabled  `dupl` linter for test package 
## Pull request type

Please check the type of change your PR introduces:
- [ ] :construction: Work in Progress
- [ ] :rainbow: Refactoring (no functional changes, no api changes)
- [ ] :hamster: Trivial/Minor
- [ ] :bug: Bugfix
- [ ] :sunflower: Feature
- [ ] :world_map: Documentation
- [ ] :robot: Test
- [ ] :building_construction: Build

## Issues 

- fixes #3034 
## Test Plan

- [ ] :muscle: Manual
- [ ] :zap: Unit test
- [ ] :green_heart: E2E

2024-08-28 12:11 UTC, anishbista60 commented
yet to fix some issue .

2024-08-28 20:09 UTC, pavannd1 commented
Same as the other PR. Please add some description to explain the changes.

2024-08-29 02:19 UTC, anishbista60 commented
> Same as the other PR. Please add some description to explain the changes.

same

2024-09-04 04:54 UTC, julio-lopez requested changes
🥇Thanks for doing this.

This is going in the right direction. It seems that it still needs work.

2024-09-04 05:53 UTC, anishbista60 commented on pkg/function/scale_test.go
> +			if action == "scaleDown" {
@julio-lopez sure

2024-09-04 05:54 UTC, anishbista60 commented
@julio-lopez I'll try to finish off these linter thing as fast as I can . Just please assist me in review❤️. Thankyou

2025-03-16 00:15 UTC, closed without merging