Add volume to vmware FcdProvider SnapshotCreate output
kanisterio/kanister pull request #770
Opened 2020-09-15 19:56 UTC by redgoat650

## Change Overview

Populate the Volume field for the `FcdProvider` `SnapshotCreate` output using the source volume.

## Pull request type

Please check the type of change your PR introduces:
- [x] :hamster: Trivial/Minor

2020-09-15 23:21 UTC, vkamra approved these changes

2020-09-16 00:00 UTC, julio-lopez requested changes

2020-09-16 00:00 UTC, julio-lopez commented on pkg/blockstorage/vmware/vmware.go
> +	snap.Volume = &volume
Since this is an expected invariant of the API contract, it makes sense to add a unit test for it.

2020-09-16 00:00 UTC, julio-lopez commented on pkg/blockstorage/vmware/vmware.go
> +	snap.Volume = &volume
@redgoat650 I know, no good deed goes unpunished. Sorry.

2020-09-16 00:05 UTC, julio-lopez approved these changes

2020-09-16 21:18 UTC, merged