Added new function for merging PodSpec
kanisterio/kanister pull request #825
Opened 2020-12-01 12:59 UTC by rahulchheda

Signed-off-by: Rahul M Chheda <rchheda@infracloud.io>

## Change Overview

## Pull request type

Please check the type of change your PR introduces:
- [ ] :construction: Work in Progress
- [ ] :rainbow: Refactoring (no functional changes, no api changes)
- [ ] :hamster: Trivial/Minor
- [ ] :bug: Bugfix
- [ ] :sunflower: Feature
- [ ] :world_map: Documentation
- [ ] :robot: Test

## Issues

- #XXX

## Test Plan

- [ ] :muscle: Manual
- [ ] :zap: Unit test
- [ ] :green_heart: E2E

2020-12-02 04:46 UTC, PrasadG193 commented on pkg/kube/pod.go
> +
Can we add tests for this?

2020-12-02 10:46 UTC, PrasadG193 approved these changes

2020-12-02 10:49 UTC, PrasadG193 commented
@rahulchheda let's not commit changes in `go.sum` to avoid conflicts

2020-12-02 10:50 UTC, rahulchheda commented
Sure, let me just run go mod tidy

2020-12-02 10:53 UTC, PrasadG193 commented
I am sure it will make things worse :D. I would suggest reverting changes in go.sum

2021-03-03 03:08 UTC, pavannd1 requested changes
Does not work!

2022-01-26 20:54 UTC, closed without merging